version: '3.7'

services:
  redis:
    image: redis:7.2
    container_name: redis
    command: redis-server
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  db:
    image: postgres:15
    container_name: db
    restart: on-failure
    env_file:
      - .env.docker
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: rabbitmq
    restart: on-failure
    env_file:
      - .env.docker
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env.docker
    depends_on:
      - redis
      - db
      - rabbitmq

volumes:
  db_data:
  redis_data:
  rabbitmq_data: