version: '3.7'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server
    restart: on-failure
    expose:
      - '6379'
    volumes:
      - redis_data:/data
  db:
    image: postgres:15-alpine
    container_name: db
    restart: on-failure
    env_file:
      - .env.docker
    expose:
      - '5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env.docker
    volumes:
      - app_logs:/fastapi_app/logs
    depends_on:
      - redis
      - db

volumes:
  db_data:
  redis_data:
  app_logs: